const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = 'qq_digest/web/templates/find_helpers.html';
assert.ok(fs.existsSync(path), 'Find helpers are available');
const scope = {escapeHtml: s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;'), localStorage: {getItem:()=>null,setItem:()=>{}}};
vm.createContext(scope);
vm.runInContext(fs.readFileSync(path,'utf8').replace(/<\/?script>/g,''),scope);
assert.equal(scope.findHighlight('<img> 配置 & 配置','配置'),'&lt;img&gt; <mark>配置</mark> &amp; <mark>配置</mark>');
assert.equal(scope.findHighlight('a.b A.B','a.b'),'<mark>a.b</mark> <mark>A.B</mark>');
assert.equal(scope.findHighlight('<script>',''),'&lt;script&gt;');
const msg=(id,minute,group=11,date='2026-10-04')=>({kind:'message',id,group_id:group,date,timestamp:`2026-10-04T03:${String(minute).padStart(2,'0')}:00Z`});
const grouped = scope.findGroupHits([msg('a',10),msg('b',8),msg('c',5),msg('d',4),msg('e',3,22),{kind:'report',id:2},msg('f',2,11,'2026-10-03')]);
assert.equal(grouped.length,5);
assert.equal(grouped[0].items.length,3);
assert.equal(grouped[1].items[0].id,'d');
assert.equal(scope.findGroupHits([{...msg('x',2),timestamp:'bad'},msg('y',1)])[0].items.length,1);
scope.localStorage.getItem=()=>'{bad'; assert.equal(scope.findReadRecent().length,0);
scope.localStorage.getItem=()=>JSON.stringify(['配置','配置',null,{},'x',...Array.from({length:9},(_,i)=>'测试'+i)]);
assert.equal(scope.findReadRecent().length,6);
assert.equal(scope.findReadRecent()[0],'配置');
let saved;scope.localStorage.setItem=(k,v)=>{saved=JSON.parse(v)};
scope.findSaveRecent('接口');assert.equal(saved[0],'接口');assert.equal(saved.length,6);
scope.localStorage.getItem=()=>{throw Error('blocked')};scope.localStorage.setItem=()=>{throw Error('blocked')};
assert.equal(scope.findReadRecent().length,0);scope.findSaveRecent('配置');
console.log('Highlight escaping, grouping boundaries and local history verified');
