const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function node(){return {value:'',hidden:true,options:[],dataset:{},style:{},isConnected:true,textContent:'',innerHTML:'',attrs:{},setAttribute(k,v){this.attrs[k]=v;},addEventListener(){},appendChild(){},focus(){},scrollIntoView(){},querySelector(){return null;},querySelectorAll(){return [];}};}
const elements={},requests=[]; const get=id=>elements[id]??=node();
get('search-kind').value='message';get('search-group').options=[{value:'',textContent:'全部群'}];
const scope={console,URLSearchParams,Date,Number,Array,JSON,Promise,String,featureFlags:{tasks:false,review:false,bookmarks:false},escapeHtml:s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;'),formatNumber:String,refreshDateHints(){},location:{search:''},history:{replaceState(){}},localStorage:{getItem(){return null},setItem(){}},document:{body:{style:{overflow:''}},getElementById:get,querySelectorAll(){return []},addEventListener(){},createElement:node},api(method,url){return new Promise((resolve,reject)=>requests.push({url,resolve,reject}));}};
vm.createContext(scope);
for(const file of ['bookmark_actions.html','message_context_script.html','find_helpers.html','find_script.html'])vm.runInContext(fs.readFileSync('qq_digest/web/templates/'+file,'utf8').replace(/<style>[\s\S]*?<\/style>/,'').replace(/<\/?script>/g,''),scope);
(async()=>{
  requests.shift().resolve({groups:[]});await new Promise(resolve=>setImmediate(resolve));
  assert.equal(requests.length,0,'Opening empty find page does not read messages or search');
  await scope.loadSearch();assert.equal(requests.length,0);
  get('search-q').value='配置';const first=scope.loadSearch();const old=requests.shift();
  get('search-q').value='接口';const second=scope.loadSearch();const latest=requests.shift();
  latest.resolve({results:[],total:0,page:1,page_size:20});await second;
  old.resolve({results:[],total:99,page:1,page_size:20});await first;
  assert.equal(get('search-count').textContent,'共 0 条匹配');
  const button=Object.assign(node(),{dataset:{group:'11',message:'m1',name:'研发群'}});
  const opening=scope.showSearchContext(button);const pending=requests.shift();scope.closeFindContext();
  pending.resolve({messages:[{msg_id:'m1',text:'旧消息',timestamp:'2026-10-04',sender_qq:123}]});await opening;
  assert.equal(get('find-context').hidden,true);assert.equal(get('find-context-body').innerHTML,'');
  const once=scope.showSearchContext(button);const r1=requests.shift();
  const twice=scope.showSearchContext(button);const r2=requests.shift();
  r2.resolve({messages:[]});await twice;r1.resolve({messages:[]});await once;scope.closeFindContext();
  assert.equal(scope.document.body.style.overflow,'','Repeated context opens restore body scrolling');
  get('search-from').value='2026-10-04';get('search-to').value='2026-10-05';const running=scope.loadSearch();const abandoned=requests.shift();
  get('search-to').value='2026-10-01';await scope.loadSearch();abandoned.resolve({results:[],total:9,page:1,page_size:20});await running;
  assert.equal(get('find-results-card').attrs['aria-busy'],'false','Invalid input cancels loading state');
  scope.location.search='?q=配置&group_id=11';
  get('search-group').appendChild=function(option){this.options.push(option);};
  vm.runInContext(fs.readFileSync('qq_digest/web/templates/find_script.html','utf8').replace(/<\/?script>/g,''),scope);
  requests.shift().reject(Error('groups unavailable'));await new Promise(resolve=>setImmediate(resolve));
  const filtered=requests.shift();assert.equal(new URLSearchParams(filtered.url.split('?')[1]).get('group_id'),'11','Group lookup failure cannot widen an existing search link');
  filtered.resolve({results:[],total:0,page:1,page_size:20});await new Promise(resolve=>setImmediate(resolve));
  assert.ok(get('find-filter-hint').textContent.includes('读取失败'));
  scope.location.search='';get('search-q').value='';
  vm.runInContext(fs.readFileSync('qq_digest/web/templates/find_script.html','utf8').replace(/<\/?script>/g,''),scope);
  get('search-q').value='尚未提交';requests.shift().resolve({groups:[]});await new Promise(resolve=>setImmediate(resolve));
  assert.equal(requests.length,0,'Late group loading must not submit draft input');
  console.log('Empty entry, stale results, context state and preserved search scope verified');
})().catch(error=>{console.error(error);process.exitCode=1;});
