const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('qq_digest/web/templates/settings.html','utf8');
const nodes=new Map([['feature-tasks',{checked:true}],['feature-auto_daily',{checked:true}],['deepseek-api-key',{value:'unsaved-synthetic-key'}]]);
global.document={getElementById:id=>nodes.get(id)};
global.savedFeatures={revision:3,catalog:[{key:'tasks',group:'扩展功能'},{key:'auto_daily',group:'自动任务'}],values:{tasks:false,auto_daily:false}};
global.featureFlags={...savedFeatures.values};global.location={href:''};
global.history={replaceState(){}};global.setFeatureFormBusy=()=>{};global.setResult=()=>{};global.updateWorkspaceTools=()=>{};global.refreshAutomaticSchedule=()=>{};
const calls=[];
global.api=(method,url,body)=>{calls.push(body);return Promise.resolve({...savedFeatures,revision:4,values:{tasks:false,auto_daily:true}});};
vm.runInThisContext(source.slice(source.indexOf('  function saveFeatureCategory('),source.indexOf("  document.getElementById('features-form').onsubmit=")));
(async()=>{
  saveFeatureCategory({preventDefault(){}},true);
  await new Promise(setImmediate);
  assert.equal(location.href,'','saving a category must not navigate away from unsaved drafts');
  assert.deepEqual(calls[0],{values:{auto_daily:true},expected_revision:3});
  assert.equal(savedFeatures.revision,4,'the next save must use the new revision');
  assert.equal(nodes.get('feature-tasks').checked,true,'other category draft stays on screen');
  assert.equal(nodes.get('deepseek-api-key').value,'unsaved-synthetic-key');
  saveFeatureCategory({preventDefault(){}},false);
  await new Promise(setImmediate);
  assert.deepEqual(calls[1],{values:{tasks:true},expected_revision:4});
  const categories=fs.readFileSync('qq_digest/web/templates/settings_categories_script.html','utf8');
  nodes.set('desktop-required',{hidden:false,dataset:{unavailable:true}});
  document.querySelectorAll=()=>[];
  history.replaceState=(_state,_title,url)=>{location.search=url.slice(url.indexOf('?'));};
  const selectedQueries=[];
  global.updateWorkspaceTools=()=>selectedQueries.push(location.search);
  vm.runInThisContext(categories.slice(categories.indexOf('  function showSettingsCategory('),categories.indexOf("\n  document.querySelectorAll('[data-settings-section]').forEach")));
  showSettingsCategory('features',true);
  showSettingsCategory('ai',true);
  assert.deepEqual(selectedQueries,['?section=features','?section=ai'],'header selection must follow category URLs without reload or save');
  console.log('Category save isolation and unsaved drafts verified');
})().catch(error=>{console.error(error);process.exitCode=1;});
