const fs=require('fs'), vm=require('vm'), assert=require('node:assert/strict');
const nodes=new Map();
function node(id){if(!nodes.has(id))nodes.set(id,{hidden:true,textContent:'',value:0,max:0,setAttribute(k,v){this[k]=v;}});return nodes.get(id);}
global.document={getElementById:node};
global.summaryGenerationBusy=false;global.summaryGenerationStarted=0;
global.updateGenerationControls=()=>{};global.setRangeBusy=()=>{};
global.summaryShowResult=()=>{};global.generationNextSteps=()=>{};const outcomes=[];global.renderSummaryOutcome=(r,s)=>outcomes.push({r,s});
let next=0;const timers=new Map();global.setTimeout=fn=>{timers.set(++next,fn);return next;};global.clearTimeout=id=>timers.delete(id);
const requests=[];global.api=(method,url)=>new Promise((resolve,reject)=>requests.push({method,url,resolve,reject}));
vm.runInThisContext(fs.readFileSync('qq_digest/web/templates/summary_progress_script.html','utf8').replace(/<\/?script>/g,''));
const base={generation_id:'abc',scope:{group_ids:[11,22,33,44,55,66,77,88,99],start_date:'2026-10-05',end_date:'2026-10-05'},status:'running',stage:'summary',total:9,completed:2,current_group:{group_name:'群三',group_id:33},elapsed_seconds:43,counts:{created:1,reused:1,skipped:0,failed:0},groups:[],result:null};
(async()=>{
  const restoring=summaryRestoreGeneration();requests.at(-1).resolve({generation:base});await restoring;
  assert.equal(summaryGenerationBusy,true,'refresh reconnects to existing job');
  assert.equal(node('summary-progress-bar').value,2);
  assert.equal(node('summary-progress-bar').max,9);
  assert.match(node('summary-progress-stage').textContent,/群三.*AI/);
  assert.match(node('range-progress-count').textContent,/2.*9/);
  assert.equal(node('range-generation-progress').hidden,false);
  const polling=summaryPollProgress('abc');const count=requests.length;
  summaryPollProgress('abc');assert.equal(requests.length,count,'polls may not overlap');
  requests.at(-1).reject(new Error('offline'));await polling;
  assert.equal(summaryGenerationBusy,true,'connection loss must not claim generation failed');
  assert.match(node('summary-progress-connection').textContent,/重连/);
  const recovering=summaryPollProgress('abc');
  const result={status:'partial_success',created_reports:[],reused_reports:[],skipped_groups:[],failed_groups:[{group_name:'群三',error:'失败'}]};
  requests.at(-1).resolve({generation:{...base,status:'partial_success',stage:'finished',completed:9,counts:{created:5,reused:2,skipped:1,failed:1},result}});await recovering;
  assert.equal(summaryGenerationBusy,false);
  assert.equal(node('summary-progress-bar').value,9);
  assert.match(node('summary-progress-stage').textContent,/部分失败/);
  assert.equal(node('summary-progress-connection').textContent,'');
  assert.equal(outcomes.length,1);
  summaryFinishProgress('abc',result,base.scope);assert.equal(outcomes.length,1,'POST and poll completion render only once');
  summaryProgressId='next';summaryProgressFinished=null;summaryGenerationBusy=true;
  const stale=summaryPollProgress('next');
  summaryDrawProgress({...base,status:'success',completed:9});
  summaryFinishProgress('next',{...result,status:'success'},base.scope);
  requests.at(-1).resolve({generation:{...base,generation_id:'next'}});await stale;
  assert.equal(node('summary-progress-bar').value,9,'older running poll must not overwrite POST completion');
  summaryProgressId='missing';summaryProgressFinished=null;summaryGenerationBusy=true;summaryProgressScope=base.scope;
  summaryDrawProgress(base);const missing=summaryPollProgress('missing');requests.at(-1).reject(Object.assign(new Error('已不存在'),{status:404}));await missing;
  assert.equal(summaryGenerationBusy,false);
  assert.equal(node('summary-progress-bar').value,2,'interrupted job preserves actual completed count');
  assert.match(node('summary-progress-stage').textContent,/中断/);
  console.log('Real group progress, refresh, non-overlapping polls, reconnect and partial completion verified');
})().catch(e=>{console.error(e);process.exitCode=1;});
