const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const nodes=new Map();
function node(id){if(!nodes.has(id))nodes.set(id,{value:'',hidden:false,disabled:false,textContent:'',children:[],appendChild(n){this.children.push(n);},focus(){},setAttribute(){}});return nodes.get(id);}
global.document={getElementById:node,createElement:tag=>({tag,appendChild(){},setAttribute(){},addEventListener(){}}),activeElement:{focus(){}},querySelectorAll:()=>[],addEventListener(){}};
global.window={addEventListener(){}};
global.summaryNode=(tag,cls,text)=>({tag,textContent:text||'',appendChild(){}});
global.summaryButton=summaryNode;const results=[];global.summaryShowResult=(...args)=>results.push(args);global.refreshDateHints=()=>{};
global.recentWeekDates=()=>({start:'2026-09-28',end:'2026-10-04'});
global.dailyResultMessage=()=>'';global.loadReports=()=>{};global.formatNumber=String;global.toast=()=>{};
const requests=[];
global.api=(method,url,body)=>new Promise((resolve,reject)=>requests.push({method,url,body,resolve,reject}));
vm.runInThisContext(fs.readFileSync('qq_digest/web/templates/summary_generation_script.html','utf8').replace(/<\/?script>/g,''));
global.selectedRangeGroupIds=()=>[11];
(async()=>{
  node('report-from').value='2026-10-03';node('report-to').value='2026-10-04';node('report-group').value='11';
  rangeGroups=[{group_id:11,name:'Synthetic',enabled:true}];
  openRangeSummary();
  assert.equal(node('range-start-date').value,'2026-10-03','first open follows reading dates');
  assert.equal(node('range-time-mode').value,'custom','arbitrary reading dates select custom');
  setRangeDates('today');
  assert.equal(node('range-start-date').value,node('range-end-date').value);
  assert.equal(node('range-time-mode').value,'today');
  setRangeDates('week');
  assert.equal(node('range-start-date').value,'2026-09-28');
  setRangeDates('custom');
  assert.equal(node('range-start-date').value,'2026-09-28','custom preserves dates');
  clearTimeout(rangePreviewTimer);
  const old=refreshRangePreview(),oldRequest=requests.at(-1);
  node('range-start-date').value='2026-10-04';
  const latest=refreshRangePreview(),latestRequest=requests.at(-1);
  latestRequest.resolve({groups:[{group_id:11,group_name:'Synthetic',message_count:0}],total_messages:0,timezone:'Asia/Shanghai'});
  await latest;
  assert.equal(node('range-submit-btn').disabled,true,'zero messages cannot start');
  oldRequest.resolve({groups:[{group_id:11,group_name:'Synthetic',message_count:100}],total_messages:100});
  await old;
  assert.equal(rangePreviewData.total_messages,0,'old response must not overwrite the current scope');
  const ready=refreshRangePreview();requests.at(-1).resolve({groups:[{group_id:11,group_name:'Synthetic',message_count:5}],total_messages:5,timezone:'Asia/Shanghai'});await ready;
  assert.equal(node('range-submit-btn').disabled,false);
  submitRangeSummary({preventDefault(){}});
  const running=requests.at(-1),count=requests.length;
  assert.equal(running.url,'/api/summaries','all presets share one generation endpoint');
  submitRangeSummary({preventDefault(){}});
  assert.equal(requests.length,count,'only one generation request may be pending');
  closeRangeSummary();
  assert.equal(node('range-summary-panel').hidden,true,'panel may close while running');
  assert.equal(summaryGenerationBusy,true,'closing does not mark the running request complete');
  running.resolve({created_reports:[],reused_reports:[],skipped_groups:[],failed_groups:[],status:'success'});
  await new Promise(setImmediate);
  assert.equal(summaryGenerationBusy,false);
  openRangeSummary();clearTimeout(rangePreviewTimer);
  assert.equal(node('range-start-date').value,'2026-10-04','reopening preserves edited selection');
  const next=refreshRangePreview();requests.at(-1).resolve({groups:[],total_messages:5});await next;
  submitRangeSummary({preventDefault(){}});const failed=requests.at(-1),failedCount=requests.length;
  submitRangeSummary({preventDefault(){}});assert.equal(requests.length,failedCount);
  failed.reject(new Error('Synthetic AI failure'));await new Promise(setImmediate);
  assert.equal(summaryGenerationBusy,false);
  assert.equal(results.at(-1)[1],'failed');
  assert.equal(node('range-open-btn').disabled,false,'range picker recovers after the request finishes');
  console.log('Scope prefill, stale preview, zero input, single generation and close while running verified');
})().catch(error=>{console.error(error);process.exitCode=1;});
