const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const nodes=new Map();
function node(id){if(!nodes.has(id))nodes.set(id,{value:'',hidden:true,options:[],children:[],dataset:{},textContent:'',innerHTML:'',isConnected:true,classList:{add(){},remove(){},toggle(){}},appendChild(n){this.children.push(n);this.options.push(n);},setAttribute(){},removeAttribute(){},scrollIntoView(){},focus(){},querySelector(){return node(id+'-child');},addEventListener(){}});return nodes.get(id);}
global.document={getElementById:node,activeElement:node('opener'),createElement:()=>node('new-'+nodes.size),querySelectorAll:()=>[],addEventListener(){}};
global.window={scrollY:120,scrollTo(){},addEventListener(){}};global.sessionStorage={setItem(){},getItem(){return null;}};
global.location={href:'http://localhost/reports',search:''};global.history={replaceState(){}};
global.requestAnimationFrame=fn=>fn();global.refreshDateHints=()=>{};global.formatNumber=String;global.escapeHtml=String;global.toast=()=>{};
const main=fs.readFileSync('qq_digest/web/templates/reports.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
vm.runInThisContext(main);
vm.runInThisContext(fs.readFileSync('qq_digest/web/templates/summary_reading_script.html','utf8').replace(/<\/?script>/g,'').replace('  summaryInit();',''));
vm.runInThisContext(fs.readFileSync('qq_digest/web/templates/summary_generation_script.html','utf8').replace(/<\/?script>/g,''));
global.recentWeekDates=()=>({start:'2026-09-29',end:'2026-10-05'});
global.closeRangeSummary=()=>{};global.destroyMessageContext=()=>{};global.featureFlags={report_revisions:false,report_qa:false};
const requests=[];global.api=(method,url)=>new Promise((resolve,reject)=>requests.push({method,url,resolve,reject}));
function browse(group,from,to,view='points'){summaryView=view;summaryDetailActive=false;node('report-detail').hidden=true;node('report-group').value=group;node('report-from').value=from;node('report-to').value=to;node('report-kind').value='all';node('summary-read-filter').value='all';}
const settle=()=>new Promise(setImmediate);
(async()=>{
  browse('22','2026-09-01','2026-09-07','groups');reportPage=3;
  summaryReadRangeResults('2026-10-05','2026-10-05',[11]);
  assert.equal(node('report-group').value,'11');
  summaryReturnToReading();
  assert.equal(summaryView,'groups','return restores previous reading mode');
  assert.equal(node('report-group').value,'22');assert.equal(node('report-from').value,'2026-09-01');assert.equal(reportPage,3);
  browse('11','2026-10-05','2026-10-05');summaryApplyView();
  assert.equal(node('summary-all-dates').hidden,false,'history is reachable in points view');
  summaryAllDates();
  assert.equal(summaryView,'groups','history opens complete report cards');
  assert.equal(node('report-group').value,'','history includes groups outside generation');
  assert.equal(node('report-from').value,'');assert.equal(node('report-to').value,'');
  assert.equal(new URL('http://localhost'+requests.at(-1).url).searchParams.has('date_from'),false);
  browse('11','2026-10-05','2026-10-05');clearReportFilters();
  assert.equal(node('report-from').value,'','clearing filters must not silently restrict history to today');
  browse('11','2026-10-05','2026-10-05');
  viewReport('daily',1);const old=requests.at(-1);
  summaryAllDates();
  old.resolve({markdown:'旧摘要',group_name:'旧群',window_start_date:'2026-09-01',window_end_date:'2026-09-01',current_version:0,evidence_items:[]});await settle();
  assert.equal(node('report-detail').hidden,true,'list navigation cancels pending detail');
  browse('','2026-09-01','2026-09-07');
  viewReport('daily',1);const first=requests.at(-1);viewReport('range',1);const second=requests.at(-1);
  second.resolve({markdown:'范围摘要',group_name:'群22',window_start_date:'2026-09-01',window_end_date:'2026-09-07',current_version:0,evidence_items:[]});await settle();
  first.resolve({markdown:'延迟旧详情',group_name:'群11',window_start_date:'2026-09-01',window_end_date:'2026-09-01',current_version:0,evidence_items:[]});await settle();
  assert.equal(qaReport.kind,'range','last selection wins, including colliding numeric report IDs');
  renderSummaryOutcome({status:'success',created_reports:[{group_id:11}],reused_reports:[],skipped_groups:[],failed_groups:[]},{group_ids:[11],start_date:'2026-10-05',end_date:'2026-10-05'});
  assert.equal(qaReport.kind,'range','generation completion keeps the old detail open');
  assert.equal(node('report-from').value,'2026-09-01','generation completion keeps the current reading scope');
  summaryApplyView();assert.equal(node('summary-reading-section').hidden,true,'background refresh cannot reveal list over detail');
  closeReport();assert.equal(summaryDetailActive,false);assert.equal(node('summary-reading-section').hidden,false);
  browse('11','2026-10-05','2026-10-05');summaryLoadPoints();const abandoned=requests.at(-1);
  summaryAllDates();requests.at(-1).resolve({total:40,page:1,page_size:20,reports:[]});await settle();
  assert.equal(node('summary-reading-pages').hidden,false);
  abandoned.reject(new Error('obsolete point failure'));await settle();
  assert.equal(node('summary-reading-pages').hidden,false,'obsolete points failure cannot disable history pagination');
  global.sessionStorage.getItem=()=>JSON.stringify({view:'points',group:'11',from:'2026-10-05',to:'2026-10-05',previousReading:{view:'groups',group:'22',from:'2026-09-01',to:'2026-09-07',kind:'all',read:'all',pointPage:1,reportPage:3,scroll:90}});
  const initialized=summaryInit();const initialGroups=requests.findLast(r=>r.url==='/api/groups'),initialVisit=requests.at(-1);
  summaryReturnToReading();assert.equal(node('report-group').value,'22');
  initialGroups.resolve({groups:[{group_id:11,name:'群11'},{group_id:22,name:'群22'}]});initialVisit.resolve({previous_viewed_at:null});await initialized;await settle();
  assert.equal(node('report-group').value,'22','initial options response must not undo return to prior group');
  assert.equal(reportPage,3);
  global.location.search='?kind=daily&id=1';
  const linked=summaryInit();const linkedGroups=requests.findLast(r=>r.url==='/api/groups'),linkedVisit=requests.at(-1);
  summaryAllDates();linkedGroups.resolve({groups:[{group_id:11,name:'群11'},{group_id:22,name:'群22'}]});linkedVisit.resolve({previous_viewed_at:null});await linked;
  assert.equal(qaReport,null,'delayed startup must not reopen a deep link after history navigation');
  assert.equal(node('report-detail').hidden,true);
  global.location.search='';global.sessionStorage.getItem=()=>null;summarySince=null;
  const fresh=summaryInit();const freshGroups=requests.findLast(r=>r.url==='/api/groups'),freshVisit=requests.at(-1);
  node('summary-read-filter').value='new';summaryFilterPoints();
  freshGroups.resolve({groups:[{group_id:11,name:'群11'},{group_id:22,name:'群22'}]});freshVisit.resolve({previous_viewed_at:'2026-10-04T10:00:00Z'});await fresh;await settle();
  assert.equal(summarySince,'2026-10-04T10:00:00Z','early new filter must retain acquired visit cutoff');
  assert.match(requests.at(-1).url,/since=2026-10-04/,'new filter is refetched with the real cutoff');
  console.log('Generation scope return, all history, pending detail cancellation, last selection and detail visibility verified');
})().catch(e=>{console.error(e);process.exitCode=1;});
